# Generated by Django 5.0.3 on 2024-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todoitems_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Completed'),
        ),
    ]
