# Generated by Django 5.0.3 on 2024-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todoitems_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoitems',
            name='priority',
            field=models.BooleanField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
