# Generated by Django 5.0.3 on 2024-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_todoitems_completed_todoitems_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
