# Generated by Django 5.0.3 on 2024-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_alter_todoitems_description_alter_todoitems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='priority',
            field=models.BooleanField(null=True, verbose_name='Priority'),
        ),
    ]
