# Generated by Django 5.0.3 on 2024-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_alter_todoitems_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='priority',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default=0, null=True, verbose_name='Priority'),
        ),
    ]
