# Generated by Django 5.0.3 on 2024-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_alter_todoitems_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='priority',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', null=True, verbose_name='Priority'),
        ),
    ]
