# Generated by Django 5.0.3 on 2024-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0019_alter_todoitems_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', null=True, verbose_name='Priority'),
        ),
    ]
