# Generated by Django 5.0.3 on 2024-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0020_alter_todoitems_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
